| security_definition                                                                                                                                                                                                                                                                         |
| ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| ALTER TABLE "public"."letters" ENABLE ROW LEVEL SECURITY;                                                                                                                                                                                                                                   |
| ALTER TABLE "public"."memory_traces" ENABLE ROW LEVEL SECURITY;                                                                                                                                                                                                                             |
| ALTER TABLE "public"."favorites" ENABLE ROW LEVEL SECURITY;                                                                                                                                                                                                                                 |
| ALTER TABLE "public"."profiles" ENABLE ROW LEVEL SECURITY;                                                                                                                                                                                                                                  |
| ALTER TABLE "public"."reports" ENABLE ROW LEVEL SECURITY;                                                                                                                                                                                                                                   |
| ALTER TABLE "public"."system_settings" ENABLE ROW LEVEL SECURITY;                                                                                                                                                                                                                           |
| ALTER TABLE "public"."stamps" ENABLE ROW LEVEL SECURITY;                                                                                                                                                                                                                                    |
| ALTER TABLE "public"."user_stamps" ENABLE ROW LEVEL SECURITY;                                                                                                                                                                                                                               |
| ALTER TABLE "public"."post_logs" ENABLE ROW LEVEL SECURITY;                                                                                                                                                                                                                                 |
| ALTER TABLE "public"."letter_reads" ENABLE ROW LEVEL SECURITY;                                                                                                                                                                                                                              |
| CREATE POLICY "誰でも読める（期限内・パブリックのみ）" ON "public"."letters" FOR SELECT TO public USING (((is_private = false) AND ((expires_at IS NULL) OR (expires_at > now()))));                                                                                                                           |
| CREATE POLICY "ログインユーザーは投稿できる" ON "public"."letters" FOR INSERT TO authenticated WITH CHECK ((auth.uid() = user_id));                                                                                                                                                                       |
| CREATE POLICY "Users can select their own favorites" ON "public"."favorites" FOR SELECT TO public USING ((auth.uid() = user_id));                                                                                                                                                           |
| CREATE POLICY "Users can insert their own favorites" ON "public"."favorites" FOR INSERT TO public WITH CHECK ((auth.uid() = user_id));                                                                                                                                                      |
| CREATE POLICY "Users can delete their own favorites" ON "public"."favorites" FOR DELETE TO public USING ((auth.uid() = user_id));                                                                                                                                                           |
| CREATE POLICY "Profiles are viewable by everyone" ON "public"."profiles" FOR SELECT TO public USING (true);                                                                                                                                                                                 |
| CREATE POLICY "Users can insert their own profile" ON "public"."profiles" FOR INSERT TO public WITH CHECK ((auth.uid() = id));                                                                                                                                                              |
| CREATE POLICY "Users can view their own stamps" ON "public"."user_stamps" FOR SELECT TO public USING ((auth.uid() = user_id));                                                                                                                                                              |
| CREATE POLICY "Users can insert their own stamps" ON "public"."user_stamps" FOR INSERT TO public WITH CHECK ((auth.uid() = user_id));                                                                                                                                                       |
| CREATE POLICY "Enable read access for all users" ON "public"."stamps" FOR SELECT TO public USING (true);                                                                                                                                                                                    |
| CREATE POLICY "Admins can do everything" ON "public"."profiles" FOR ALL TO public USING ((is_admin = true));                                                                                                                                                                                |
| CREATE POLICY "Anyone can insert reports" ON "public"."reports" FOR INSERT TO public WITH CHECK (true);                                                                                                                                                                                     |
| CREATE POLICY "Admins can view reports" ON "public"."reports" FOR SELECT TO public USING ((( SELECT profiles.is_admin
   FROM profiles
  WHERE (profiles.id = auth.uid())) = true));                                                                                                        |
| CREATE POLICY "Admins can view all letters" ON "public"."letters" FOR SELECT TO public USING ((( SELECT profiles.is_admin
   FROM profiles
  WHERE (profiles.id = auth.uid())) = true));                                                                                                    |
| CREATE POLICY "Users can manage their own stamps" ON "public"."user_stamps" FOR ALL TO authenticated USING ((auth.uid() = user_id)) WITH CHECK ((auth.uid() = user_id));                                                                                                                    |
| CREATE POLICY "ユーザーは自分の手紙を削除できる" ON "public"."letters" FOR DELETE TO public USING ((auth.uid() = user_id));                                                                                                                                                                                 |
| CREATE POLICY "管理者はすべての手紙を削除できる" ON "public"."letters" FOR DELETE TO public USING ((auth.email() = ANY (ARRAY['marei.suyama@gmail.com'::text, 'contact@volvox-ltd.com'::text])));                                                                                                           |
| CREATE POLICY "管理者はすべての手紙を編集できる" ON "public"."letters" FOR UPDATE TO public USING ((auth.email() = ANY (ARRAY['marei.suyama@gmail.com'::text, 'contact@volvox-ltd.com'::text]))) WITH CHECK ((auth.email() = ANY (ARRAY['marei.suyama@gmail.com'::text, 'contact@volvox-ltd.com'::text]))); |
| CREATE POLICY "1日1通制限" ON "public"."letters" FOR INSERT TO authenticated WITH CHECK (check_daily_letter_limit());                                                                                                                                                                           |
| CREATE POLICY "管理者は切手をすべて操作できる" ON "public"."stamps" FOR ALL TO public USING ((auth.email() = ANY (ARRAY['marei.suyama@gmail.com'::text, 'contact@volvox-ltd.com'::text]))) WITH CHECK ((auth.email() = ANY (ARRAY['marei.suyama@gmail.com'::text, 'contact@volvox-ltd.com'::text])));      |
| CREATE POLICY "ログインユーザーは自分の既読を保存できる" ON "public"."letter_reads" FOR INSERT TO authenticated WITH CHECK ((auth.uid() = user_id));                                                                                                                                                            |
| CREATE POLICY "ログインユーザーは自分の既読を確認できる" ON "public"."letter_reads" FOR SELECT TO authenticated USING ((auth.uid() = user_id));                                                                                                                                                                 |
| CREATE POLICY "既読の参照を許可" ON "public"."letter_reads" FOR SELECT TO public USING (true);                                                                                                                                                                                                      |
| CREATE POLICY "既読の保存を許可" ON "public"."letter_reads" FOR INSERT TO public WITH CHECK (true);                                                                                                                                                                                                 |
| CREATE POLICY "Enable read access for all users" ON "public"."letters" FOR SELECT TO public USING (true);                                                                                                                                                                                   |
| CREATE POLICY "Enable update for authenticated users" ON "public"."letters" FOR UPDATE TO authenticated USING (true) WITH CHECK (true);                                                                                                                                                     |
| CREATE POLICY "Enable delete for authenticated users" ON "public"."letters" FOR DELETE TO authenticated USING (true);                                                                                                                                                                       |
| CREATE POLICY "Admin full access" ON "public"."letters" FOR INSERT TO authenticated WITH CHECK (((auth.jwt() ->> 'email'::text) = ANY (ARRAY['marei.suyama@gmail.com'::text, 'contact@volvox-ltd.com'::text])));                                                                            |
| CREATE POLICY "User limited insert" ON "public"."letters" FOR INSERT TO authenticated WITH CHECK (((is_official = false) AND (is_post = false) AND (user_id = auth.uid())));                                                                                                                |
| CREATE POLICY "Admin full access by ID" ON "public"."letters" FOR ALL TO authenticated USING ((auth.uid() = 'a31a7fd3-85b9-4fbc-a57f-2f9e6ec6c999'::uuid));                                                                                                                                 |
| CREATE POLICY "Users can view own logs" ON "public"."post_logs" FOR SELECT TO public USING ((auth.uid() = user_id));                                                                                                                                                                        |
| CREATE POLICY "Users can insert own logs" ON "public"."post_logs" FOR INSERT TO public WITH CHECK ((auth.uid() = user_id));                                                                                                                                                                 |
| CREATE POLICY "Users can see their own traces" ON "public"."memory_traces" FOR SELECT TO authenticated USING ((auth.uid() = user_id));                                                                                                                                                      |
| CREATE POLICY "Everyone can see thread traces" ON "public"."memory_traces" FOR SELECT TO authenticated USING (((user_id IS NULL) AND (is_thread = true)));                                                                                                                                  |