create table public.favorites (
  id bigint generated by default as identity not null,
  user_id uuid not null,
  letter_id uuid not null,
  created_at timestamp with time zone not null default timezone ('utc'::text, now()),
  constraint favorites_pkey primary key (id),
  constraint favorites_user_id_letter_id_key unique (user_id, letter_id),
  constraint favorites_letter_id_fkey foreign KEY (letter_id) references letters (id) on delete CASCADE,
  constraint favorites_user_id_fkey foreign KEY (user_id) references auth.users (id) on delete CASCADE
) TABLESPACE pg_default;

create table public.letter_reads (
  id bigint generated by default as identity not null,
  letter_id uuid not null,
  user_id uuid null,
  created_at timestamp with time zone not null default timezone ('utc'::text, now()),
  constraint letter_reads_pkey primary key (id),
  constraint letter_reads_letter_id_fkey foreign KEY (letter_id) references letters (id) on delete CASCADE,
  constraint letter_reads_user_id_fkey foreign KEY (user_id) references auth.users (id) on delete CASCADE
) TABLESPACE pg_default;

create trigger trigger_deposit_trace_on_read
after INSERT on letter_reads for EACH row
execute FUNCTION deposit_memory_trace ();

create table public.letters (
  id uuid not null default gen_random_uuid (),
  title text not null,
  spot_name text not null,
  lat double precision not null,
  lng double precision not null,
  content text null,
  image_url text null,
  user_id uuid null,
  is_private boolean null default false,
  expires_at timestamp with time zone null,
  created_at timestamp with time zone null default now(),
  is_official boolean null default false,
  password text null,
  attached_stamp_id bigint null,
  is_post boolean null default false,
  parent_id uuid null,
  is_postcard boolean null default false,
  allow_reply boolean null default true,
  constraint letters_pkey primary key (id),
  constraint letters_attached_stamp_id_fkey foreign KEY (attached_stamp_id) references stamps (id),
  constraint letters_parent_id_fkey foreign KEY (parent_id) references letters (id) on delete CASCADE,
  constraint letters_user_id_fkey foreign KEY (user_id) references auth.users (id) on delete CASCADE
) TABLESPACE pg_default;

create index IF not exists idx_letters_created_at on public.letters using btree (created_at) TABLESPACE pg_default;

create index IF not exists idx_letters_parent_id on public.letters using btree (parent_id) TABLESPACE pg_default;

create index IF not exists idx_letters_user_id on public.letters using btree (user_id) TABLESPACE pg_default;

create trigger on_letter_created_increment_count
after INSERT on letters for EACH row
execute FUNCTION increment_total_post_count ();

create trigger trigger_deposit_trace_on_reply
after INSERT on letters for EACH row
execute FUNCTION deposit_memory_trace ();

create trigger trigger_deposit_trace_on_write
after INSERT on letters for EACH row
execute FUNCTION deposit_memory_trace ();

create table public.memory_traces (
  id uuid not null default gen_random_uuid (),
  user_id uuid null,
  lat double precision not null,
  lng double precision not null,
  is_thread boolean null default false,
  created_at timestamp with time zone null default now(),
  constraint memory_traces_pkey primary key (id)
) TABLESPACE pg_default;

create table public.post_logs (
  id uuid not null default gen_random_uuid (),
  user_id uuid null,
  post_id uuid null,
  created_at timestamp with time zone not null default now(),
  constraint post_logs_pkey primary key (id),
  constraint post_logs_post_id_fkey foreign KEY (post_id) references letters (id) on delete CASCADE,
  constraint post_logs_user_id_fkey foreign KEY (user_id) references auth.users (id) on delete CASCADE
) TABLESPACE pg_default;

create index IF not exists idx_post_logs_user_post_date on public.post_logs using btree (user_id, post_id, created_at) TABLESPACE pg_default;

create table public.profiles (
  id uuid not null,
  nickname text not null,
  created_at timestamp with time zone not null default timezone ('utc'::text, now()),
  is_admin boolean null default false,
  email text null,
  total_post_count integer null default 0,
  constraint profiles_pkey primary key (id),
  constraint profiles_nickname_key unique (nickname),
  constraint profiles_id_fkey foreign KEY (id) references auth.users (id) on delete CASCADE
) TABLESPACE pg_default;

create trigger "send-welcome-email"
after INSERT on profiles for EACH row
execute FUNCTION supabase_functions.http_request (
  'https://fevsactrqsfxazatyzqu.supabase.co/functions/v1/welcome-email',
  'POST',
  '{"Content-type":"application/json","Authorization":"Bearer <YOUR_TOKEN>"}',
  '{}',
  '5000'
);

create table public.reports (
  id bigint generated by default as identity not null,
  letter_id uuid null,
  reporter_id uuid null,
  reason text null,
  created_at timestamp with time zone null default now(),
  constraint reports_pkey primary key (id),
  constraint reports_letter_id_fkey foreign KEY (letter_id) references letters (id) on delete CASCADE,
  constraint reports_reporter_id_fkey foreign KEY (reporter_id) references auth.users (id)
) TABLESPACE pg_default;

create table public.stamps (
  id bigint generated by default as identity not null,
  name text not null,
  image_url text not null,
  description text null,
  created_at timestamp with time zone not null default timezone ('utc'::text, now()),
  constraint stamps_pkey primary key (id)
) TABLESPACE pg_default;

create table public.system_settings (
  key text not null,
  value text null,
  updated_at timestamp with time zone null default now(),
  constraint system_settings_pkey primary key (key)
) TABLESPACE pg_default;

create table public.user_stamps (
  id bigint generated by default as identity not null,
  user_id uuid not null,
  stamp_id bigint not null,
  obtained_at timestamp with time zone not null default timezone ('utc'::text, now()),
  count integer null default 1,
  last_obtained_at timestamp with time zone null default now(),
  post_id uuid null,
  constraint user_stamps_pkey primary key (user_id, stamp_id),
  constraint user_stamps_user_id_post_id_key unique (user_id, post_id),
  constraint user_stamps_post_id_fkey foreign KEY (post_id) references letters (id),
  constraint user_stamps_stamp_id_fkey foreign KEY (stamp_id) references stamps (id),
  constraint user_stamps_user_id_fkey foreign KEY (user_id) references auth.users (id) on delete CASCADE
) TABLESPACE pg_default;