| triggers_definition                                                                                                                                                                                                                                                                                          |
| ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ |
| CREATE TRIGGER update_objects_updated_at BEFORE UPDATE ON storage.objects FOR EACH ROW EXECUTE FUNCTION storage.update_updated_at_column();                                                                                                                                                                  |
| CREATE TRIGGER prefixes_create_hierarchy BEFORE INSERT ON storage.prefixes FOR EACH ROW WHEN ((pg_trigger_depth() < 1)) EXECUTE FUNCTION storage.prefixes_insert_trigger();                                                                                                                                  |
| CREATE TRIGGER enforce_bucket_name_length_trigger BEFORE INSERT OR UPDATE OF name ON storage.buckets FOR EACH ROW EXECUTE FUNCTION storage.enforce_bucket_name_length();                                                                                                                                     |
| CREATE TRIGGER objects_insert_create_prefix BEFORE INSERT ON storage.objects FOR EACH ROW EXECUTE FUNCTION storage.objects_insert_prefix_trigger();                                                                                                                                                          |
| CREATE TRIGGER objects_delete_delete_prefix AFTER DELETE ON storage.objects FOR EACH ROW EXECUTE FUNCTION storage.delete_prefix_hierarchy_trigger();                                                                                                                                                         |
| CREATE TRIGGER objects_update_create_prefix BEFORE UPDATE ON storage.objects FOR EACH ROW WHEN (((new.name <> old.name) OR (new.bucket_id <> old.bucket_id))) EXECUTE FUNCTION storage.objects_update_prefix_trigger();                                                                                      |
| CREATE TRIGGER prefixes_delete_hierarchy AFTER DELETE ON storage.prefixes FOR EACH ROW EXECUTE FUNCTION storage.delete_prefix_hierarchy_trigger();                                                                                                                                                           |
| CREATE TRIGGER tr_check_filters BEFORE INSERT OR UPDATE ON realtime.subscription FOR EACH ROW EXECUTE FUNCTION realtime.subscription_check_filters();                                                                                                                                                        |
| CREATE TRIGGER trigger_deposit_trace_on_reply AFTER INSERT ON public.letters FOR EACH ROW EXECUTE FUNCTION deposit_memory_trace();                                                                                                                                                                           |
| CREATE TRIGGER on_auth_user_created AFTER INSERT ON auth.users FOR EACH ROW EXECUTE FUNCTION handle_new_user();                                                                                                                                                                                              |
| CREATE TRIGGER on_letter_created_increment_count AFTER INSERT ON public.letters FOR EACH ROW EXECUTE FUNCTION increment_total_post_count();                                                                                                                                                                  |
| CREATE TRIGGER "send-welcome-email" AFTER INSERT ON public.profiles FOR EACH ROW EXECUTE FUNCTION supabase_functions.http_request('https://fevsactrqsfxazatyzqu.supabase.co/functions/v1/welcome-email', 'POST', '{"Content-type":"application/json","Authorization":"Bearer <YOUR_TOKEN>"}', '{}', '5000'); |
| CREATE TRIGGER trigger_deposit_trace_on_read AFTER INSERT ON public.letter_reads FOR EACH ROW EXECUTE FUNCTION deposit_memory_trace();                                                                                                                                                                       |
| CREATE TRIGGER trigger_deposit_trace_on_write AFTER INSERT ON public.letters FOR EACH ROW EXECUTE FUNCTION deposit_memory_trace();                                                                                                                                                                           |